
FROM peterx7803/ctsp-00-ros


# First clone mit-apc2016-system

WORKDIR /home/nvidia
#RUN git config --global http.postBuffer 1048576000 \
#    && git clone https://github.com/Sensing-Intelligent-System/ctsphub-workshop-2018 -b peterx-devel

COPY /01-ICP /home/nvidia/ctsphub-workshop-2018/04-perception/01-ICP

# catkin_make
WORKDIR /home/nvidia/ctsphub-workshop-2018/04-perception/01-ICP/catkin_ws
RUN /bin/bash -c "source /opt/ros/kinetic/setup.bash && catkin_make"

WORKDIR /home/nvidia
COPY custom_sr300_fps_10.launch /home/nvidia/custom_sr300_fps_10.launch

WORKDIR /home/nvidia/ctsphub-workshop-2018/04-perception/01-ICP/catkin_ws
# setup env
CMD [ "sh", "-c", "/bin/bash && source /home/nvidia/ctsphub-workshop-2018/04-perception/01-ICP/catkin_ws/devel/setup.sh" ]


