
FROM peterx7803/ctsp-02-marvin


# First clone mit-apc2016-system

WORKDIR /home/nvidia
#RUN git config --global http.postBuffer 1048576000 \
#    && git clone https://github.com/Sensing-Intelligent-System/ctsphub-workshop-2018 -b peterx-devel

COPY /02-marvin  /home/nvidia/ctsphub-workshop-2018/04-perception/02-marvin 

# catkin_make
WORKDIR /home/nvidia/ctsphub-workshop-2018/04-perception/02-marvin/catkin_ws
RUN /bin/bash -c "source /opt/ros/kinetic/setup.bash && catkin_make"

WORKDIR /home/nvidia/ctsphub-workshop-2018/04-perception/02-marvin/catkin_ws/src/marvin_convnet/models/competition


RUN /bin/bash -c "source /home/nvidia/ctsphub-workshop-2018/04-perception/02-marvin/catkin_ws/src/marvin_convnet/models/competition/download_weights.sh"

WORKDIR /home/nvidia/ctsphub-workshop-2018/04-perception/02-marvin/catkin_ws
# setup env
CMD [ "sh", "-c", "/bin/bash && source /home/nvidia/ctsphub-workshop-2018/04-perception/02-marvin/catkin_ws/devel/setup.sh" ]


